### Site Settings ###
title               : Kazuki Takeyama | Portfolio
description         : >-                               # >- means to ignore newlines until "url:"
                      Hi, I am a software engineer at Rakuten.
                      Feel free to contact me from any of the links below.


#url                 : "https://ktakeyama12.github.io"                               # base hostname & protocol for your site (e.g. http://example.com)
#baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
#remote_theme       : YoussefRaafatNasry/portfolYOU@v2.0.0    # uncomment this if you are using it as a remote theme
#repository          : ktakeyama12/ktakeyama12.github.io    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#
url : ""
baseurl             : "/portfolYOU"                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]


#repository          : YoussefRaafatNasry/portfolYOU    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]

### Author Info ###
author:
  name              : Kazuki Takeyama
  image             : ./profile.JPG
#  behance           : your_username
# dribbble          : your_username
  email             : ktakeyama12@gmail.com
#  facebook          : your_username
  github            : ktakeyama12
# gitlab            : your_username
# instagram         : your_username
  linkedin          : ktakeyama12
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


## Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


## Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


## Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
- _site